services:
  development:
    build:
      context: ../dockerfiles/development
      args:
        APT_SOURCES: ${APT_SOURCES}
    env_file: .env
    volumes:
      - type: bind
        source: ..
        target: /workspace
    working_dir: /workspace
    command: [sleep, infinity]
