services:
  build:
    volumes:
      - type: bind
        source: ..
        target: /workspace
    working_dir: /workspace
    env_file: .env
    build:
      context: .
      args:
        APT_SOURCES: ${APT_SOURCES}
    command: [ /bin/bash, -eux, build-script/build.sh ]
